# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='permission',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'vip用户'), (4, '管理员'), (8, '超级管理员')], default=1, verbose_name='权限'),
        ),
    ]
