# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20180815_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app3.IdCard'),
        ),
    ]
