# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_boy_girl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='语种')),
                ('history', models.IntegerField(max_length=5, verbose_name='出现历史')),
                ('u_number', models.IntegerField(max_length=10, verbose_name='使用人数')),
            ],
        ),
    ]
