# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkk', '0002_car_siji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='engineer',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
