# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20180814_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('birthday', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': '信息表',
                'verbose_name': '修改名字',
            },
        ),
    ]
